### ISSUE TITLE
Stable-ish version?

### ISSUE THREAD

**Issue by ShakedDovrat** [voize-gmbh/pytorch-lite-multiplatform#14]
Hi guys,
Thank you for creating this valuable library.
I know you are at an early stage of developement, but I would like to use this ASAP so I would like to hear from you if you think you have a stable-enough version for doing some inference on pretty standard nets, nothing too fancy.

**Comment by erksch** [comment]
Hey, thank you for your interest!

Yes, we are still early in development and are planning to rewrite the API to abstract the `IValue` concept, thus making it more powerful and allowing more inference use cases. Currently, you might have to change your module structure if you don't only use float or long tensors as input and output, this constraint would vanish with the new IValue API. 

But nonetheless, if your modules are already so simple that the current API is sufficient or if changing your module is no big deal, I would not hesitate to give it a try! The breaking changes that will follow should be fairly easy to migrate.

And as soon as we have IValue support we can think about hitting a stable version.

**Comment by erksch** [comment]
@ShakedDovrat closing, feel free to open another issue if the current functionality does not suite your needs
