### ISSUE TITLE
symbol(s) not found for architecture x86_64 Error

### ISSUE THREAD

**Issue by CloverRedspot** [voize-gmbh/pytorch-lite-multiplatform#15]
Hello.

Using:
>macOS
pytorch-lite-multiplatform v0.4.0 (same thing on v0.3.3) 

I added a class with simple method (similar to @Test itCanRunForward) in commonMain folder.
After the build i am adding the framework from path:
> /pytorch-lite-multiplatform-main/build/bin/iosX64/podDebugFramework

to a new swift project in Xcode and call this method.
When building the Xcode project on simulator device it fails on error:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TorchModule", referenced from:
      objc-class-ref in pytorch_lite_multiplatform(result.o)
  "_OBJC_CLASS_$_Tensor", referenced from:
      objc-class-ref in pytorch_lite_multiplatform(result.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Thank you.

**Comment by erksch** [comment]
Seems like the LibTorchWrapper is not linked properly on the simulator, does it work for a real device? 
I will add an example project to the repo that should clear things up.

**Comment by CloverRedspot** [comment]
> does it work for a real device?

No. its the same:
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_TorchModule", referenced from:
      objc-class-ref in pytorch_lite_multiplatform(result.o)
  "_OBJC_CLASS_$_Tensor", referenced from:
      objc-class-ref in pytorch_lite_multiplatform(result.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by erksch** [comment]
Did you add the [pre-link gradle task](https://github.com/voize-gmbh/pytorch-lite-multiplatform/blob/main/build.gradle.kts#L91) as in the `build.gradle.kts` of the project?

**Comment by erksch** [comment]
@CloverRedspot please check out my updated comment. The info was also added to the README

**Comment by CloverRedspot** [comment]
- bitcode is disabled
- Podfile does not exists (its an empty new swift or objc project)
- I am building directly from this repository code project so all the parts you mentioned are already there. (my simple class was added inside pytorch-lite-multiplatform project)

**Comment by erksch** [comment]
I am not able to understand how your setup works. Please use a standard Kotlin multiplatform project that uses the published artifacts. We now have an example project in the repository that you can check out for reference.

**Comment by erksch** [comment]
@CloverRedspot have you been able to resolve your issue? If so, I'd close this issue

**Comment by erksch** [comment]
Closing
